# Generated by Django 3.1 on 2020-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address_data', models.EmailField(max_length=254, unique=True)),
                ('password_data', models.TextField()),
                ('companytype_data', models.CharField(max_length=100)),
                ('title_data', models.CharField(max_length=100)),
            ],
        ),
    ]
